export { default as deleteIcon } from "./delete.svg";
export { default as endSvg } from "./end.svg";
export { default as Frame } from "./Frame.svg";
export { default as hamburger } from "./hamburger.svg";
export { default as leftIcon } from "./left-icon.svg";
export { default as more } from "./more.svg";
export { default as pin } from "./pin.svg";
export { default as rightIcon } from "./right-icon.svg";
export { default as saveIcon, default as saveIconSvg } from "./save-icon.svg";
export { default as searchIcon } from "./search-icon.svg";
export { default as startSvg } from "./start.svg";
export { default as plusSvg, default as Vector } from "./Vector.svg";
